# Generated by Django 3.1.3 on 2021-04-06 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hometuitionapp', '0004_auto_20210406_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherstudentfee',
            old_name='payment_data',
            new_name='payment_date',
        ),
    ]
