# Generated by Django 3.1.3 on 2021-04-08 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hometuitionapp', '0006_auto_20210407_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiring',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hometuitionapp.subject'),
        ),
    ]
