# Generated by Django 3.1.3 on 2021-04-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hometuitionapp', '0007_hiring_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiring',
            name='user',
        ),
    ]
