# Generated by Django 3.1.3 on 2021-04-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometuitionapp', '0009_hiring_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiring',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hiring',
            name='payment_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hiring',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
