# Generated by Django 3.1.3 on 2021-04-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometuitionapp', '0010_auto_20210408_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiring',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
