# Generated by Django 3.1.3 on 2021-04-09 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hometuitionapp', '0012_auto_20210408_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketraise',
            name='receiver_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'hometuitionapp'), ('model', 'hometuitionsystem')), on_delete=django.db.models.deletion.CASCADE, related_name='trreceivers', to='contenttypes.contenttype'),
        ),
    ]
